[[plugins]]
# 文字前後修飾
repo = 'tpope/vim-surround'

[[plugins]]
# ステータスラインに情報表示
repo = 'itchyny/lightline.vim'
hook_add = '''
  set laststatus=2 " ステータスラインを常に表示
  set showmode " 現在のモードを表示
  set showcmd " 打ったコマンドをステータスラインの下に表示
  set ruler " ステータスラインの右側にカーソルの現在位置を表示する
'''

[[plugins]]
# インデントの可視化
repo = 'Yggdroot/indentLine'


[[plugins]]
# virtualenv 環境のPythonを利用
repo = 'jmcantrell/vim-virtualenv'

[[plugins]]
# python 構文チェック
repo = 'scrooloose/syntastic'
hook_add= '''
  let g:syntastic_python_checkers = ['pyflakes']
'''

[[plugins]]
# python 補完
repo = 'davidhalter/jedi-vim'

[[plugins]]
# scalaプラグイン
repo = 'derekwyatt/vim-scala'

[[plugins]]
# Markdownプラグイン
repo = 'plasticboy/vim-markdown'
hook_add = '''
  " md もmarkdownファイルとみなす
  au BufRead,BufNewFile *.md set filetype=markdown
'''

[[plugins]]
# git プラグイン
repo = 'tpope/vim-fugitive'
hook_add = '''
  set statusline+=%{fugitive#statusline()}
'''

[[plugins]]
# ファイラ
repo = 'Shougo/unite.vim'
hook_add = '''
  " close vimfiler automatically when there are only vimfiler open
  autocmd MyAutoCmd BufEnter * if (winnr('$') == 1 && &filetype ==# 'vimfiler') | q | endif
  let g:vimfiler_as_default_explorer = 1
  let g:vimfiler_enable_auto_cd = 1
  let g:vimfiler_ignore_pattern = "\%(\.pyc$\)"
'''
